# Quick Test Race - 1 minute test run
# Perfect for testing the system before building TUI

race:
  name: "Quick Test Race - System Validation"

  # Short test parameters (1 minute)
  duration: 60     # 1 minute only
  users: 5         # 5 concurrent users per engine
  spawn_rate: 2.0  # Spawn 2 users per second

  # Workload configuration
  dataset: "sharegpt"  # Conversational dataset
  target_input_tokens: 256
  target_output_tokens: 128

  # Output configuration
  output_dir: "results/races"

  # Real cluster engines
  engines:
    - name: "vllm"
      url: "https://vllm-test-vllm-benchmark.apps.cluster-njnqr.njnqr.sandbox1049.opentlc.com"
      model: "meta-llama/Llama-3.2-3B-Instruct"
      emoji: "🚀"
      color: "bright_blue"
      tokenizer: "meta-llama/Llama-3.2-3B-Instruct"

    - name: "tgi"
      url: "http://tgi-test-vllm-benchmark.apps.cluster-njnqr.njnqr.sandbox1049.opentlc.com"
      model: "meta-llama/Llama-3.2-3B-Instruct"
      emoji: "🤖"
      color: "bright_magenta"
      tokenizer: "meta-llama/Llama-3.2-3B-Instruct"

